import { NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { z } from "zod";
import { getProductById, type Product } from "@/lib/products";

const QuoteRequestSchema = z.object({
  customer: z.object({
    name: z.string().min(1).max(200),
    email: z.string().email().max(254),
    phone: z.string().max(50).optional().nullable(),
    country: z.string().min(1).max(120),
    address: z.string().max(500).optional().nullable(),
  }),
  notes: z.string().max(2000).optional().nullable(),
  consent: z.boolean(),
  cart: z.object({
    items: z
      .array(
        z.object({
          productId: z.string().min(1),
          quantity: z.number().int().min(1).max(50),
        })
      )
      .min(1),
  }),
});

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`Missing required env var: ${name}`);
  return value;
}

function formatMoney(n: number) {
  return `$${n.toFixed(0)}`;
}

type ResolvedItem = {
  product: Product;
  quantity: number;
  lineTotal: number;
};

export async function POST(req: Request) {
  try {
    const json = await req.json();

    const parsed = QuoteRequestSchema.safeParse(json);
    if (!parsed.success) {
      return NextResponse.json(
        { ok: false, message: "Invalid request", issues: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const { customer, notes, consent, cart } = parsed.data;

    const resolvedItems: Array<ResolvedItem | null> = cart.items.map((line) => {
      const product = getProductById(line.productId);
      if (!product) return null;
      return {
        product,
        quantity: line.quantity,
        lineTotal: product.price * line.quantity,
      };
    });

    const items: ResolvedItem[] = resolvedItems.filter(
      (x): x is ResolvedItem => x !== null
    );

    if (items.length === 0) {
      return NextResponse.json(
        { ok: false, message: "Cart items could not be resolved." },
        { status: 400 }
      );
    }

    const subtotal = items.reduce((sum, i) => sum + i.lineTotal, 0);
    const orderId = `QT-${Math.random().toString(16).slice(2, 8).toUpperCase()}`;

    const smtpHost = requireEnv("SMTP_HOST");
    const smtpPort = Number(process.env.SMTP_PORT ?? "587");
    const smtpUser = requireEnv("SMTP_USER");
    const smtpPass = requireEnv("SMTP_PASS");
    const quoteTo = requireEnv("QUOTE_TO_EMAIL");
    const siteName = process.env.SITE_NAME ?? "Aegis Wellness";

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const cartLinesText = items
      .map((i) => `- ${i.product.name} (x${i.quantity}) = ${formatMoney(i.lineTotal)}`)
      .join("\n");

    const emailLines: Array<string | null> = [
      `New quote request (${orderId})`,
      "",
      `Customer: ${customer.name}`,
      `Email: ${customer.email}`,
      customer.phone ? `Phone: ${customer.phone}` : null,
      `Country: ${customer.country}`,
      customer.address ? `Address: ${customer.address}` : null,
      "",
      `Estimated subtotal: ${formatMoney(subtotal)}`,
      `Items:\n${cartLinesText}`,
      notes ? `Notes:\n${notes}` : null,
      "",
      `Consent: ${consent ? "true" : "false"}`,
      "",
      `Generated by ${siteName}. No payment collected via this flow.`,
    ];

    const emailText = emailLines.filter(Boolean).join("\n");

    await transporter.sendMail({
      from: process.env.SMTP_FROM ?? smtpUser,
      to: quoteTo,
      subject: `${siteName} - Quote request (${orderId})`,
      text: emailText,
    });

    return NextResponse.json({ ok: true, orderId });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown server error";
    return NextResponse.json({ ok: false, message }, { status: 500 });
  }
}
